apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: he-letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: totally@svaha.com
    privateKeySecretRef:
      name: letsencrypt-staging
  solvers:
    - dns01:
        webhook:
          solverName: he
          groupName: acme.xdb.me
          config:
            heUrl: 'https://dns.he.net' # URL for operations. Default (and probably the only valid value): "https://dns.he.net"
            method: 'dynamic-dns' # method to use. "login" is also the default
            # only if you use secrets
            credentialsSecretRef:
              name: 'he-credentials' # name of secret. Default: "he-credentials"
              namespace:
                'cert-manager' # optional namespace for the secret. If not given, the secret is
                # looked for in the issuer namespace.
                # For a ClusterIssuer, specify this or the release namespace (eg,
                # `cert-manager`) will be used.
