apiVersion: v1
kind: PersistentVolume
metadata:
  name: transient-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Ti
  nfs:
    path: /mnt/mpool/Media
    server: freenasty.infra.falcone.us
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
status: {}
