apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: narthex-gateway
  namespace: narthex
spec:
  addresses:
    - type: IPAddress
      value: 10.0.1.245
  gatewayClassName: cilium
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: Same
      name: https
      port: 443
      protocol: HTTPS
