apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: narthex-gateway
  namespace: narthex
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  addresses:
    - type: IPAddress
      value: 10.0.1.245
  gatewayClassName: cilium
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: Same
      name: plex
      port: 32400
      protocol: HTTPS
      hostname: 'narthaplex.snellarcade.org' # ✅ Required.
      tls:
        mode: Terminate # ✅ Required. "Terminate" is the only supported mode.
        certificateRefs:
          - name: wildcard-snellarcade-org-tls # ✅ Required.
            kind: Secret # ✅ Optional. "Secret" is the only valid value.
            group: '' # ✅ Optional. "" is the only valid value.
    - allowedRoutes:
        namespaces:
          from: Same
          # from: All
      name: https
      port: 443
      protocol: HTTPS
      hostname: '*.snellarcade.org' # ✅ Required.
      tls:
        mode: Terminate # ✅ Required. "Terminate" is the only supported mode.
        certificateRefs:
          - name: wildcard-snellarcade-org-tls # ✅ Required.
            kind: Secret # ✅ Optional. "Secret" is the only valid value.
            group: '' # ✅ Optional. "" is the only valid value.
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: narthaplex-tls
spec:
  hostnames:
    - narthaplex.snellarcade.org
    - narthaplex.lebastion.snellarcade.org
  parentRefs:
    - name: narthex-gateway
      sectionName: plex
      namespace: narthex
  rules:
    - backendRefs:
        - name: plex-narthaplex
          port: 32400
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: snellarcade-http-filter-redirect
spec:
  parentRefs:
    - name: narthex-gateway
      kind: Gateway
      sectionName: http
      namespace: narthex
  hostnames:
    - '*.snellarcade.org'
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
            port: 443
