bpf:
  masquerade: false
debug:
  enabled: true
  verbose: flow
externalIPs:
  enabled: true
gatewayAPI:
  enabled: true
  hostNetwork:
    enabled: true
envoy:
  enabled: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy:
        # Add NET_BIND_SERVICE to the list (keep the others!)
        - NET_BIND_SERVICE
    privileged: true
hostPort:
  enabled: true
hostServices:
  enabled: false
hubble:
  enabled: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - icmp
      - http
  relay:
    enabled: true
  ui:
    enabled: true
image:
  pullPolicy: IfNotPresent
ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16
k8sClientRateLimit:
  burst: 20
  qps: 10
k8sServiceHost: localhost
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
  enabled: true
loadBalancer:
  serviceTopology: true
operator:
  prometheus:
    enabled: true
  replicas: 1
prometheus:
  enabled: true
